name: Film & Series M3U Playlist Generator

on:
  push:
    branches: [ main, master ]
  schedule:
    # Genera playlist automaticamente ogni giorno alle 6:00 UTC
    - cron: '0 6 * * *'

env:
  PYTHON_VERSION: "3.11"

jobs:
  generate-playlists:
    name: Generate M3U Playlists
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests>=2.31.0 python-dotenv>=1.0.0

    - name: Generate movie playlist
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        echo "🎬 Running film.py..."
        python film.py

    - name: Generate series playlist
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        echo "📺 Running serie.py..."
        python serie.py

    - name: List generated files
      run: |
        echo "📊 Generated files:"
        ls -la *.m3u *.json 2>/dev/null || echo "No files generated"

    - name: Upload playlists
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playlists-${{ github.run_number }}
        path: |
          *.m3u
          *_cache.json
        retention-days: 30

    - name: Create release (on schedule)
      if: github.event_name == 'schedule'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: auto-${{ github.run_number }}
        name: "Playlists $(date +'%Y-%m-%d')"
        body: |
          🎬 Playlist generate automaticamente il $(date +'%d/%m/%Y')
          
          - Film playlist (film.py)
          - Serie TV playlist (serie.py)
        files: |
          *.m3u
          *_cache.json
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
